[versions]
kotlin = "1.6.10"

arrow = "1.0.1"
jgit = "6.0.0.202111291000-r"
kotest = "5.0.3"
semverCore = "0.1.0-beta.10"

gradle-benmanes-versions = "0.41.0"
gradle-changelog = "1.11.1"
gradle-pluginPublish = "0.19.0"
github-release = "2.2.12"
gradle-semverPlugin = "0.0.23"

[libraries]
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
javiersc-semver-semverCore = { module = "com.javiersc.semver:semver-core", version.ref = "semverCore" }
eclipse-jgit-eclipseJgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm" ]

[plugins]
changelog = { id = "org.hildan.github.changelog", version.ref = "gradle-changelog" }
githubrelease = { id = "com.github.breadmoirai.github-release", version.ref = "github-release" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-pluginPublish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
semver = { id = "io.github.nefilim.gradle.semver-plugin", version.ref = "gradle-semverPlugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-benmanes-versions" }
