[versions]
kotlin = "1.6.10"

arrow = "1.0.1"
github-release = "2.2.12"
jgit = "6.0.0.202111291000-r"
kotest = "5.0.3"
semverCore = "0.1.0-beta.10"
semverPlugin = "0.0.9"

[libraries]
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
javiersc-semver-semverCore = { module = "com.javiersc.semver:semver-core", version.ref = "semverCore" }
eclipse-jgit-eclipseJgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm" ]

[plugins]
gradlePluginPublish = { id = "com.gradle.plugin-publish", version = "0.18.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
semver = { id = "io.github.nefilim.gradle.semver-plugin", version.ref = "semverPlugin" }
githubrelease = { id = "com.github.breadmoirai.github-release", version.ref = "github-release" }